apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/redis

patches:
- target:
    kind: StatefulSet
    name: redis
  patch: |
    - op: replace
      path: /spec/template/spec/volumes
      value:
        - name: redis-data
          hostPath:
            path: /Users/dmoreno/Documents/unergy/originabot/redis-data
            type: DirectoryOrCreate
  
- target:
    kind: StatefulSet
    name: redis
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          cpu: "200m"
          memory: "1Gi"