apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/nginx

patches:
- target:
    kind: Deployment
    name: nginx
  patch: |
    - op: replace
      path: /spec/template/spec/volumes
      value:
        - name: nginx-conf
          configMap:
            name: nginx-config
        - name: nginx-html
          configMap:
            name: nginx-html
        - name: static
          hostPath:
            path: /Users/dmoreno/Documents/unergy/the-sun-factory/instances/static
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: /Users/dmoreno/Documents/unergy/the-sun-factory/instances/media
            type: DirectoryOrCreate