apiVersion: v1
kind: Service
metadata:
  name: originabot
  namespace: default
spec:
  type: NodePort
  selector:
    app: originabot
  ports:
    - name: http
      protocol: TCP
      port: 8000     
      nodePort: 30001