apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - prometheus
  - grafana
  - kube-state-metrics

# Configuraciones comunes
commonLabels:
  app.kubernetes.io/part-of: monitoring