apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml

commonLabels:
  app.kubernetes.io/name: kube-state-metrics
  app.kubernetes.io/part-of: monitoring