apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/rabbitmq

patches:
- target:
    kind: Deployment
    name: rabbitmq
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "400m"
          memory: "512Mi"

configMapGenerator:
- name: rabbitmq-config
  behavior: create
  literals:
    - RABBITMQ_DEFAULT_USER="guest"
    - RABBITMQ_DEFAULT_PASS="guest"