apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: default
  labels:
    app: auth

spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
      - name: auth
        image: auth
        imagePullPolicy: Never

        ports:
        - containerPort: 8080
          name: http
        command: [
          "gunicorn", "auth.wsgi:application", 
          "--name", "auth", 
          "--workers", "$(WORKERS)", 
          "--timeout", "120", 
          "--bind", "0.0.0.0:8080", 
          "--forwarded-allow-ips", "*"
        ]
        
        envFrom:
        - configMapRef:
            name: auth-config