apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- celery/deployment.yaml
- celery-beat/deployment.yaml
- grpc/deployment.yaml
- grpc/service.yaml