apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: default
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30000