---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-celery-beat
  namespace: default
  labels:
    app: auth-celery-beat

spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-celery-beat
  template:
    metadata:
      labels:
        app: auth-celery-beat
        
    spec:
      containers:
      - name: auth-celery-beat
        image: auth
        imagePullPolicy: Never
        command: ["celery", "-A", "auth", "beat", "--loglevel=info"]

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"

        envFrom:
        - configMapRef:
            name: auth-config