apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/database

patches:
- target:
    kind: StatefulSet
    name: postgres
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "400m"
          memory: "512Mi"

configMapGenerator:
- name: postgres-config
  behavior: create
  literals:
    - POSTGRES_DB="originabotdb"
    - POSTGRES_USER="postgres"
    - POSTGRES_PASSWORD="postgres"