apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - pvc.yaml

commonLabels:
  app.kubernetes.io/name: prometheus