apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-grpc
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-grpc
  template:
    metadata:
      labels:
        app: auth-grpc
    spec:
      containers:
      - name: auth-grpc
        image: auth
        imagePullPolicy: Never
        command: ["sh", "-c", "python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. auth.proto && python3 server.py"]
        
        ports:
        - containerPort: 50051
          name: auth-grpc

        envFrom:
        - configMapRef:
            name: auth-config

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"