apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: monitoring
data:
  grafana.ini: |-
    [server]
    domain = localhost
    root_url = %(protocol)s://%(domain)s/grafana/
    serve_from_sub_path = true
    
    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    
    [auth]
    disable_login_form = false
    
    [analytics]
    check_for_updates = true
    
    [log]
    mode = console
    level = info