apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: monitoring
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: monitoring
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:9.5.2
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin  # En producción, usar un secreto
        - name: GF_INSTALL_PLUGINS
          value: "grafana-piechart-panel,grafana-worldmap-panel"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards-provider
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
        - name: grafana-ini
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-storage
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboards-provider
        configMap:
          name: grafana-dashboards-provider
          items:
            - key: dashboards-provider.yaml
              path: provider.yaml
      - name: grafana-dashboards
        projected:
          sources:
            - configMap:
                name: grafana-dashboards-provider
                items:
                  - key: kubernetes-cluster-monitoring-dashboard.json
                    path: kubernetes-cluster-monitoring.json
                  - key: pod-detailed-dashboard.json
                    path: pod-detailed-dashboard.json
            - configMap:
                name: grafana-kube-state-metrics-dashboard
                items:
                  - key: kube-state-metrics-dashboard.json
                    path: kube-state-metrics-dashboard.json
            - configMap:
                name: grafana-http-requests-dashboard
                items:
                  - key: http-requests-dashboard.json
                    path: http-requests-dashboard.json
      - name: grafana-ini
        configMap:
          name: grafana-ini