apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap-datasources.yaml
  - configmap-dashboards-provider.yaml
  - configmap-grafana-ini.yaml
  - configmap-kube-state-metrics-dashboard.yaml
  - configmap-http-requests-dashboard.yaml
  - pvc.yaml

commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/part-of: monitoring